SELECT
    MEMBER_ID,
    MEMEBER_NAME,
    AGE,
    GENDER,
    CITY,
    JOIN_DATE,
    TOTAL_TRANSACTIONS,
    TOTAL_SPENT,
    TOTAL_VISITS,
    CASE WHEN TOTAL_SPENT>80000 OR TOTAL_VISITS>10 THEN 'HIGH'
    WHEN TOTAL_SPENT BETWEEN 10000 AND 50000 THEN 'MEDIUM'
    ELSE 'LOW' END AS RISK_LEVEL
FROM {{ref("int_member_profile")}}
